Repository siteorigin/siteorigin-north, pull requests merged in 2019-10, with the labels that each got.

#374 Prevent long titles overlapping remove icon
  sass/woocommerce/_cart.scss
  woocommerce.css
Labels: bug, priority-2

#375 Switched footer separators to hyphens
  footer.php
  inc/template-tags.php
  sass/site/primary/_footer.scss
  style.css
Labels: enhancement

#377 Exclude Logo from LiteSpeed Cache lazy loading
  inc/template-tags.php
Labels: bug

#379 Delcare heading sizes
  sass/typography/_headings.scss
  style.css
Labels: enhancement
